name: project_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management  
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # cache data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # firebase
  firebase_core: ^3.2.0

  # authentication
  firebase_auth: ^5.1.2

  # database
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.1

  # router
  go_router: ^14.2.1

  # navigation bar
  google_nav_bar: ^5.0.6

  # localization
  easy_localization: ^3.0.7

  # network
  connectivity_plus: ^6.0.4

  # other
  uuid: ^4.4.2
  image_picker: ^1.1.2
  flutter_image_compress: ^1.1.0
  image: ^4.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf


  assets:
    - assets/translations/

